### ISSUE TITLE
Issue due to non-existant directories after install

### ISSUE THREAD

**Issue by himynamesdave** [signalscorps/obstracts-cli#1]
Tested using a mac.

When I run script for first time (after install) I get error

```
main.py", line 69, in <module>
    fs = FileSystemStore("stix2_extractions")
  File "/Users/dgreenwood/Documents/GitHub/obstracts-cli/obstracts-cli/lib/python3.9/site-packages/stix2/datastore/filesystem.py", line 524, in __init__
    source=FileSystemSource(stix_dir=stix_dir, allow_custom=allow_custom_source, encoding=encoding),
  File "/Users/dgreenwood/Documents/GitHub/obstracts-cli/obstracts-cli/lib/python3.9/site-packages/stix2/datastore/filesystem.py", line 659, in __init__
    raise ValueError("directory path for STIX data does not exist: %s" % self._stix_dir)
ValueError: directory path for STIX data does not exist: /Users/dgreenwood/Documents/GitHub/obstracts-cli/stix2_extractions
```

If I create directory  /Users/dgreenwood/Documents/GitHub/obstracts-cli/stix2_extractions I then get error

```
main.py", line 75, in <module>
    with open(stix_bundle_path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'stix2_reports/bundle--dba6cb85-f074-491e-af30-716416938c33.json'
```

which is resolved if i create directory  /Users/dgreenwood/Documents/GitHub/obstracts-cli/stix2_reports

**Comment by shanthanu9** [comment]
Hey, the same code seems to be working in my Linux system, so I am not exactly sure what is going wrong. I suspect it might be because I am using relative paths in code.

I have updated beta-1 branch to use absolute folder paths in code. Can you please pull the latest changes and check if it's working now?
